# Generated by Django 4.2.30 on 2026-09-15 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bussiness_tables', '0003_remove_bussiness_tables_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('CUSTOMER', 'Khách hàng'), ('STAFF', 'Nhân viên'), ('SYSTEM', 'Hệ thống')], default='CUSTOMER', max_length=20)),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='bussiness_tables.bussiness_tables')),
            ],
            options={
                'db_table': 'table_chat_messages',
                'ordering': ['created_at'],
            },
        ),
    ]
