# Generated by Django 4.2 on 2026-07-29 17:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_options_alter_orderdetail_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
