# Generated by Django 4.2.30 on 2026-09-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_avatar',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
