import random
from django.db import migrations


def seed_100_products(apps, schema_editor):
    try:
        Categories = apps.get_model("categories", "Categories")
    except LookupError:
        Categories = apps.get_model("products", "Categories")

    Product = apps.get_model("products", "Product")

    # Danh sách 100 sản phẩm có sẵn link ảnh cụ thể cho từng món
    raw_products = [
        # --- CÀ PHÊ (15 món) ---
        (
            "Cà phê đen đá",
            "Cà phê",
            25000,
            "Ly",
            "Cà phê đen truyền thống đậm vị",
            "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=500&auto=format&fit=crop",
        ),
        (
            "Cà phê sữa đá",
            "Cà phê",
            30000,
            "Ly",
            "Cà phê pha phin kết hợp sữa đặc",
            "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=500&auto=format&fit=crop",
        ),
        (
            "Bạc xỉu nóng/lạnh",
            "Cà phê",
            35000,
            "Ly",
            "Nhiều sữa ít cà phê ngọt dịu",
            "https://images.unsplash.com/photo-1541167760496-1628856ab772?w=500&auto=format&fit=crop",
        ),
        (
            "Espresso Single",
            "Cà phê",
            35000,
            "Cốc",
            "Espresso Ý nguyên chất",
            "https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?w=500&auto=format&fit=crop",
        ),
        (
            "Espresso Double",
            "Cà phê",
            45000,
            "Cốc",
            "Đôi Shot Espresso đậm đà",
            "https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?w=500&auto=format&fit=crop",
        ),
        (
            "Americano Đá",
            "Cà phê",
            40000,
            "Ly",
            "Espresso pha loãng với nước đá",
            "https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?w=500&auto=format&fit=crop",
        ),
        (
            "Cappuccino Nóng",
            "Cà phê",
            45000,
            "Cốc",
            "Espresso cùng bọt sữa mịn",
            "https://images.unsplash.com/photo-1534778101976-62847782c213?w=500&auto=format&fit=crop",
        ),
        (
            "Latte Macchiato",
            "Cà phê",
            50000,
            "Ly",
            "Cà phê Latte tầng bọt sữa",
            "https://images.unsplash.com/photo-1570968915860-54d5c301fa9f?w=500&auto=format&fit=crop",
        ),
        (
            "Mocha Caramel",
            "Cà phê",
            52000,
            "Ly",
            "Espresso, sốt chocolate và caramel",
            "https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=500&auto=format&fit=crop",
        ),
        (
            "Cà phê Muối",
            "Cà phê",
            35000,
            "Ly",
            "Cà phê kem muối béo ngậy chuẩn vị",
            "https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?w=500&auto=format&fit=crop",
        ),
        (
            "Cà phê Trứng",
            "Cà phê",
            45000,
            "Cốc",
            "Cà phê phin hòa quyện kem trứng Hà Nội",
            "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=500&auto=format&fit=crop",
        ),
        (
            "Cà phê Cốt dừa",
            "Cà phê",
            48000,
            "Ly",
            "Cà phê đá xay cùng nước cốt dừa",
            "https://images.unsplash.com/photo-1541167760496-1628856ab772?w=500&auto=format&fit=crop",
        ),
        (
            "Cold Brew Truyền thống",
            "Cà phê",
            45000,
            "Chai",
            "Cà phê ủ lạnh 16 tiếng",
            "https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?w=500&auto=format&fit=crop",
        ),
        (
            "Cold Brew Cam Sả",
            "Cà phê",
            50000,
            "Ly",
            "Cà phê ủ lạnh kết hợp mứt cam tươi",
            "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=500&auto=format&fit=crop",
        ),
        (
            "Affogato Cà phê",
            "Cà phê",
            45000,
            "Phần",
            "Kem vani tưới shot Espresso nóng",
            "https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?w=500&auto=format&fit=crop",
        ),

        # --- TRÀ & TRÀ SỮA (18 món) ---
        (
            "Trà Đào Cam Sả",
            "Trà & Trà sữa",
            38000,
            "Ly",
            "Trà đào thanh mát thêm vị cam sả",
            "https://images.unsplash.com/photo-1558857563-b371033873b8?w=500&auto=format&fit=crop",
        ),
        (
            "Trà Vải Hạt Chia",
            "Trà & Trà sữa",
            38000,
            "Ly",
            "Trà vải ngọt nhẹ kèm hạt chia",
            "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=500&auto=format&fit=crop",
        ),
        (
            "Trà Dâu Tây Kem Cheese",
            "Trà & Trà sữa",
            45000,
            "Ly",
            "Trà dâu tươi phủ lớp kem phô mai",
            "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=500&auto=format&fit=crop",
        ),
        (
            "Trà Tắc Mật Ong",
            "Trà & Trà sữa",
            30000,
            "Ly",
            "Trà tắc đậm đà kết hợp mật ong rừng",
            "https://images.unsplash.com/photo-1597481499750-3e6b22637e12?w=500&auto=format&fit=crop",
        ),
        (
            "Trà Sen Vàng",
            "Trà & Trà sữa",
            48000,
            "Ly",
            "Trà oolong thanh mát hạt sen giòn ngọt",
            "https://images.unsplash.com/photo-1558857563-b371033873b8?w=500&auto=format&fit=crop",
        ),
        (
            "Trà Mãng Cầu Tươi",
            "Trà & Trà sữa",
            42000,
            "Ly",
            "Trà mãng cầu xiêm chua ngọt chuẩn trend",
            "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=500&auto=format&fit=crop",
        ),
        (
            "Trà Hoa Cúc Mật Ong",
            "Trà & Trà sữa",
            35000,
            "Tách",
            "Trà hoa cúc nóng thanh nhiệt giải độc",
            "https://images.unsplash.com/photo-1597481499750-3e6b22637e12?w=500&auto=format&fit=crop",
        ),
        (
            "Trà Matcha Latte",
            "Trà & Trà sữa",
            48000,
            "Ly",
            "Matcha Nhật Bản kết hợp sữa tươi",
            "https://images.unsplash.com/photo-1536256263959-770b48d82b0a?w=500&auto=format&fit=crop",
        ),
        (
            "Trà Sữa Trân Châu Đường Đen",
            "Trà & Trà sữa",
            45000,
            "Ly",
            "Sữa tươi trân châu đường đen ngậy béo",
            "https://images.unsplash.com/photo-1558857563-b371033873b8?w=500&auto=format&fit=crop",
        ),
        (
            "Trà Sữa Ô Long Nướng",
            "Trà & Trà sữa",
            42000,
            "Ly",
            "Trà sữa đậm vị trà ô long nướng",
            "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=500&auto=format&fit=crop",
        ),
        (
            "Trà Sữa Thái Xanh",
            "Trà & Trà sữa",
            35000,
            "Ly",
            "Trà sữa Thái thơm lừng kèm thạch xanh",
            "https://images.unsplash.com/photo-1536256263959-770b48d82b0a?w=500&auto=format&fit=crop",
        ),
        (
            "Trà Sữa Thái Đỏ",
            "Trà & Trà sữa",
            35000,
            "Ly",
            "Trà sữa Thái đỏ truyền thống",
            "https://images.unsplash.com/photo-1558857563-b371033873b8?w=500&auto=format&fit=crop",
        ),
        (
            "Hồng Trà Macchiato",
            "Trà & Trà sữa",
            40000,
            "Ly",
            "Hồng trà cốt đậm phủ váng sữa đậm đà",
            "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=500&auto=format&fit=crop",
        ),
        (
            "Trà Bưởi Hồng Đỏ",
            "Trà & Trà sữa",
            42000,
            "Ly",
            "Trà bưởi hồng tươi thanh lọc cơ thể",
            "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=500&auto=format&fit=crop",
        ),
        (
            "Trà Chanh Giã Tay",
            "Trà & Trà sữa",
            32000,
            "Ly",
            "Chanh Quảng Đông giã tay thơm lừng",
            "https://images.unsplash.com/photo-1597481499750-3e6b22637e12?w=500&auto=format&fit=crop",
        ),
        (
            "Trà Kiều Mạch Sữa",
            "Trà & Trà sữa",
            40000,
            "Ly",
            "Trà kiều mạch thơm mùi ngũ cốc hạt",
            "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=500&auto=format&fit=crop",
        ),
        (
            "Trà Sữa Đậu Đỏ",
            "Trà & Trà sữa",
            42000,
            "Ly",
            "Trà sữa truyền thống topping đậu đỏ",
            "https://images.unsplash.com/photo-1558857563-b371033873b8?w=500&auto=format&fit=crop",
        ),
        (
            "Trà Long Nhãn Hạt Bột Lọc",
            "Trà & Trà sữa",
            45000,
            "Ly",
            "Trà nhãn ngọt thanh kèm bột lọc bọc nhãn",
            "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=500&auto=format&fit=crop",
        ),

        # --- SINH TỐ & NƯỚC ÉP (15 món) ---
        (
            "Sinh Tố Bơ Dừa",
            "Sinh tố & Nước ép",
            45000,
            "Ly",
            "Sinh tố bơ sáp Daklak nguyên chất",
            "https://images.unsplash.com/photo-1613478223719-2ab802602423?w=500&auto=format&fit=crop",
        ),
        (
            "Sinh Tố Xoài Cát",
            "Sinh tố & Nước ép",
            40000,
            "Ly",
            "Sinh tố xoài chín cây thơm ngọt",
            "https://images.unsplash.com/photo-1553530666-ba11a7da3888?w=500&auto=format&fit=crop",
        ),
        (
            "Sinh Tố Dâu Tây",
            "Sinh tố & Nước ép",
            48000,
            "Ly",
            "Dâu tây Đà Lạt xay cùng sữa chua",
            "https://images.unsplash.com/photo-1622597467836-f3285f2131b7?w=500&auto=format&fit=crop",
        ),
        (
            "Sinh Tố Sapoche (Hồng Xiêm)",
            "Sinh tố & Nước ép",
            38000,
            "Ly",
            "Sinh tố sapoche béo ngọt đậm đà",
            "https://images.unsplash.com/photo-1613478223719-2ab802602423?w=500&auto=format&fit=crop",
        ),
        (
            "Sinh Tố Mãng Cầu",
            "Sinh tố & Nước ép",
            42000,
            "Ly",
            "Sinh tố mãng cầu chua ngọt giải nhiệt",
            "https://images.unsplash.com/photo-1553530666-ba11a7da3888?w=500&auto=format&fit=crop",
        ),
        (
            "Sinh Tố Dừa Đá Xay",
            "Sinh tố & Nước ép",
            40000,
            "Ly",
            "Dừa tươi đá xay béo ngậy",
            "https://images.unsplash.com/photo-1613478223719-2ab802602423?w=500&auto=format&fit=crop",
        ),
        (
            "Nước Ép Cam Tươi",
            "Sinh tố & Nước ép",
            35000,
            "Ly",
            "Nước ép cam sành nguyên chất 100%",
            "https://images.unsplash.com/photo-1613478223719-2ab802602423?w=500&auto=format&fit=crop",
        ),
        (
            "Nước Ép Dưa Hấu",
            "Sinh tố & Nước ép",
            30000,
            "Ly",
            "Dưa hấu đỏ mọng nước giải khát",
            "https://images.unsplash.com/photo-1553530666-ba11a7da3888?w=500&auto=format&fit=crop",
        ),
        (
            "Nước Ép Táo Ép Lạnh",
            "Sinh tố & Nước ép",
            42000,
            "Ly",
            "Nước ép táo Fuji không thêm đường",
            "https://images.unsplash.com/photo-1622597467836-f3285f2131b7?w=500&auto=format&fit=crop",
        ),
        (
            "Nước Ép Thơm (Dứa)",
            "Sinh tố & Nước ép",
            32000,
            "Ly",
            "Dứa mật ép tươi bổ sung Vitamin C",
            "https://images.unsplash.com/photo-1553530666-ba11a7da3888?w=500&auto=format&fit=crop",
        ),
        (
            "Nước Ép Cà Rốt Mật Ong",
            "Sinh tố & Nước ép",
            35000,
            "Ly",
            "Cà rốt tươi ép bổ mắt",
            "https://images.unsplash.com/photo-1613478223719-2ab802602423?w=500&auto=format&fit=crop",
        ),
        (
            "Nước Ép Ổi Hồng",
            "Sinh tố & Nước ép",
            32000,
            "Ly",
            "Ổi xá lị ép thơm thanh mát",
            "https://images.unsplash.com/photo-1622597467836-f3285f2131b7?w=500&auto=format&fit=crop",
        ),
        (
            "Nước Ép Củ Dền Cần Tây",
            "Sinh tố & Nước ép",
            45000,
            "Ly",
            "Nước ép Healthy detox cơ thể",
            "https://images.unsplash.com/photo-1613478223719-2ab802602423?w=500&auto=format&fit=crop",
        ),
        (
            "Nước Dừa Tươi Nguyên Trái",
            "Sinh tố & Nước ép",
            30000,
            "Trái",
            "Dừa xiêm Bến Tre ngọt mát",
            "https://images.unsplash.com/photo-1553530666-ba11a7da3888?w=500&auto=format&fit=crop",
        ),
        (
            "Nước Cần Tây Táo Green Detox",
            "Sinh tố & Nước ép",
            48000,
            "Ly",
            "Detox giảm cân cần tây và táo xanh",
            "https://images.unsplash.com/photo-1622597467836-f3285f2131b7?w=500&auto=format&fit=crop",
        ),

        # --- MÓN ĂN CHÍNH (17 món) ---
        (
            "Phở Bò Tái Lăn",
            "Món ăn chính",
            65000,
            "Bát",
            "Phở bò truyền thống nước dùng đậm đà",
            "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=500&auto=format&fit=crop",
        ),
        (
            "Phở Gà Ta Thịt Đùi",
            "Món ăn chính",
            55000,
            "Bát",
            "Phở gà ta lá chanh thơm phức",
            "https://images.unsplash.com/photo-1585032226651-759b368d7246?w=500&auto=format&fit=crop",
        ),
        (
            "Bún Bò Huế Đặc Biệt",
            "Món ăn chính",
            65000,
            "Bát",
            "Bún bò Huế giò heo chả cua đầy đặn",
            "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&auto=format&fit=crop",
        ),
        (
            "Bún Chả Hà Nội",
            "Món ăn chính",
            60000,
            "Phần",
            "Chả nướng than hoa ăn kèm bún tươi",
            "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=500&auto=format&fit=crop",
        ),
        (
            "Bánh Mì Thịt Nướng Barbecue",
            "Món ăn chính",
            35000,
            "Ổ",
            "Bánh mì kẹp thịt nướng sốt đặc biệt",
            "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=500&auto=format&fit=crop",
        ),
        (
            "Bánh Mì Chảo Đắc Biệt",
            "Món ăn chính",
            55000,
            "Chảo",
            "Bánh mì chảo trứng ốp la, xíu mại, pate",
            "https://images.unsplash.com/photo-1585032226651-759b368d7246?w=500&auto=format&fit=crop",
        ),
        (
            "Cơm Tấm Sườn Bì Chả",
            "Món ăn chính",
            58000,
            "Đĩa",
            "Cơm tấm sườn nướng mỡ hành đậm đà",
            "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&auto=format&fit=crop",
        ),
        (
            "Cơm Chiên Dương Châu",
            "Món ăn chính",
            55000,
            "Đĩa",
            "Cơm chiên lạp xưởng tôm tơi xốp",
            "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=500&auto=format&fit=crop",
        ),
        (
            "Cơm Gà Xối Mỡ",
            "Món ăn chính",
            60000,
            "Đĩa",
            "Gà xối mỡ giòn rụm kèm cơm cà chua",
            "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=500&auto=format&fit=crop",
        ),
        (
            "Mì Quảng Gà Ta",
            "Món ăn chính",
            50000,
            "Bát",
            "Mì Quảng đậm đà ăn kèm bánh tráng giòn",
            "https://images.unsplash.com/photo-1585032226651-759b368d7246?w=500&auto=format&fit=crop",
        ),
        (
            "Bún Riêu Cua Đóng Gạch",
            "Món ăn chính",
            50000,
            "Bát",
            "Bún riêu cua đồng đậu hũ giò lụa",
            "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&auto=format&fit=crop",
        ),
        (
            "Hủ Tiếu Nam Vang Tôm Mực",
            "Món ăn chính",
            60000,
            "Bát",
            "Hủ tiếu nước dùng xương tôm tươi",
            "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=500&auto=format&fit=crop",
        ),
        (
            "Bún Thịt Nướng Chả Giò",
            "Món ăn chính",
            50000,
            "Tô",
            "Bún tươi thịt nướng chả giò mỡ hành",
            "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=500&auto=format&fit=crop",
        ),
        (
            "Mì Xào Hải Sản Sa Tế",
            "Món ăn chính",
            65000,
            "Đĩa",
            "Mì xào tôm mực rau củ sa tế cay",
            "https://images.unsplash.com/photo-1585032226651-759b368d7246?w=500&auto=format&fit=crop",
        ),
        (
            "Miến Gà Trộn Hà Nội",
            "Món ăn chính",
            55000,
            "Tô",
            "Miến trộn thịt gà xé phay hành phi",
            "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&auto=format&fit=crop",
        ),
        (
            "Cơm Bò Lúc Lắc Quán",
            "Món ăn chính",
            70000,
            "Đĩa",
            "Bò lúc lắc mềm ngon kèm khoai tây chiên",
            "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=500&auto=format&fit=crop",
        ),
        (
            "Mì Ý Sốt Bò Băm Spaghetti",
            "Món ăn chính",
            68000,
            "Đĩa",
            "Spaghetti sốt cà chua thịt bò băm",
            "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=500&auto=format&fit=crop",
        ),

        # --- MÓN ĂN VẶT (15 món) ---
        (
            "Khoai Tây Chiên Bơ Tỏi",
            "Món ăn vặt",
            35000,
            "Đĩa",
            "Khoai tây giòn rụm lắc bơ tỏi",
            "https://images.unsplash.com/photo-1576107232684-1279f3908594?w=500&auto=format&fit=crop",
        ),
        (
            "Cá Viên Chiên Mắm Tỏi",
            "Món ăn vặt",
            40000,
            "Phần",
            "Cá viên chiên sốt mắm tỏi cay ngọt",
            "https://images.unsplash.com/photo-1561758033-d89a9ad46330?w=500&auto=format&fit=crop",
        ),
        (
            "Bánh Khoai Môn Lệ Phố",
            "Món ăn vặt",
            35000,
            "Đĩa",
            "Bánh khoai môn nhân nhân đậu xanh giòn",
            "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=500&auto=format&fit=crop",
        ),
        (
            "Nem Chua Rán Hà Nội",
            "Món ăn vặt",
            45000,
            "Phần",
            "Nem chua rán chuẩn vị phố cổ",
            "https://images.unsplash.com/photo-1576107232684-1279f3908594?w=500&auto=format&fit=crop",
        ),
        (
            "Gà Popcorn Lắc Phô Mai",
            "Món ăn vặt",
            48000,
            "Phần",
            "Thịt gà viên chiên xù lắc bột phô mai",
            "https://images.unsplash.com/photo-1561758033-d89a9ad46330?w=500&auto=format&fit=crop",
        ),
        (
            "Phô Mai Que Chiên Giòn",
            "Món ăn vặt",
            38000,
            "Phần",
            "Phô mai que kéo sợi béo ngậy (4 que)",
            "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=500&auto=format&fit=crop",
        ),
        (
            "Xúc Xích Đức Nướng Than",
            "Món ăn vặt",
            30000,
            "Cây",
            "Xúc xích Đức nướng thơm lừng",
            "https://images.unsplash.com/photo-1576107232684-1279f3908594?w=500&auto=format&fit=crop",
        ),
        (
            "Bánh Tráng Trộn Sài Gòn",
            "Món ăn vặt",
            25000,
            "Phần",
            "Bánh tráng trộn bò khô trứng cút",
            "https://images.unsplash.com/photo-1561758033-d89a9ad46330?w=500&auto=format&fit=crop",
        ),
        (
            "Bánh Tráng Nướng Đà Lạt",
            "Món ăn vặt",
            30000,
            "Cái",
            "Bánh tráng nướng trứng phô mai xúc xích",
            "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=500&auto=format&fit=crop",
        ),
        (
            "Chả Giò Hải Sản Sốt Mayonnaise",
            "Món ăn vặt",
            45000,
            "Đĩa",
            "Chả giò chiên xù nhân hải sản",
            "https://images.unsplash.com/photo-1576107232684-1279f3908594?w=500&auto=format&fit=crop",
        ),
        (
            "Há Cảo Hấp Tôm Thịt",
            "Món ăn vặt",
            40000,
            "Xửng",
            "Há cáo Triều Châu hấp nóng 5 viên",
            "https://images.unsplash.com/photo-1561758033-d89a9ad46330?w=500&auto=format&fit=crop",
        ),
        (
            "Xíu Mại Nướng Sốt Cà",
            "Món ăn vặt",
            35000,
            "Chén",
            "Xíu mại thịt heo sốt cà chua ăn kèm bánh mì",
            "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=500&auto=format&fit=crop",
        ),
        (
            "Chân Gà Sả Tắc Cay",
            "Món ăn vặt",
            55000,
            "Đĩa",
            "Chân gà rút xương ngâm sả tắc ớt",
            "https://images.unsplash.com/photo-1576107232684-1279f3908594?w=500&auto=format&fit=crop",
        ),
        (
            "Tokbokki Sốt Cay Hàn Quốc",
            "Món ăn vặt",
            50000,
            "Tô",
            "Bánh gạo Hàn Quốc chả cá sốt gochujang",
            "https://images.unsplash.com/photo-1561758033-d89a9ad46330?w=500&auto=format&fit=crop",
        ),
        (
            "Gỏi Cuốn Tôm Thịt (3 Cuốn)",
            "Món ăn vặt",
            35000,
            "Đĩa",
            "Gỏi cuốn tôm thịt chấm tương đen",
            "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=500&auto=format&fit=crop",
        ),

        # --- TRÁNG MIỆNG & BÁNH (12 món) ---
        (
            "Bánh Tiramisu Truyền Thống",
            "Tráng miệng & Bánh",
            45000,
            "Cái",
            "Bánh Tiramisu hương cà phê cacao",
            "https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=500&auto=format&fit=crop",
        ),
        (
            "Cheesecake Chanh Dây",
            "Tráng miệng & Bánh",
            48000,
            "Cái",
            "Bánh phô mai nướng vị chanh dây chua ngọt",
            "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=500&auto=format&fit=crop",
        ),
        (
            "Bánh Mousse Dâu Tây",
            "Tráng miệng & Bánh",
            45000,
            "Cái",
            "Bánh Mousse mềm mịn vị dâu",
            "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=500&auto=format&fit=crop",
        ),
        (
            "Bánh Croissant Bơ Tỏi",
            "Tráng miệng & Bánh",
            35000,
            "Cái",
            "Bánh sừng bò nướng bơ tỏi thơm lừng",
            "https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=500&auto=format&fit=crop",
        ),
        (
            "Bánh Donut Chocolate",
            "Tráng miệng & Bánh",
            28000,
            "Cái",
            "Donut phủ lớp chocolate đắng nhẹ",
            "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=500&auto=format&fit=crop",
        ),
        (
            "Chè Thái Thập Cẩm",
            "Tráng miệng & Bánh",
            35000,
            "Ly",
            "Chè Thái sầu riêng mít nhãn sương sa",
            "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=500&auto=format&fit=crop",
        ),
        (
            "Chè Bưởi An Giang",
            "Tráng miệng & Bánh",
            30000,
            "Bát",
            "Chè bưởi đậu xanh giòn ngon nước cốt dừa",
            "https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=500&auto=format&fit=crop",
        ),
        (
            "Chè Khúc Bạch Trái Cây",
            "Tráng miệng & Bánh",
            38000,
            "Bát",
            "Khúc bạch phô mai ăn kèm hạnh nhân nhãn",
            "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=500&auto=format&fit=crop",
        ),
        (
            "Sữa Chua Nếp Cẩm",
            "Tráng miệng & Bánh",
            28000,
            "Hũ",
            "Sữa chua nhà làm ăn kèm nếp cẩm Tây Bắc",
            "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=500&auto=format&fit=crop",
        ),
        (
            "Flan Caramel Nước Cốt Dừa",
            "Tráng miệng & Bánh",
            20000,
            "Cái",
            "Bánh flan trứng mềm mịn cà phê đá",
            "https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=500&auto=format&fit=crop",
        ),
        (
            "Sữa Chua Hạt Dẻ Cười",
            "Tráng miệng & Bánh",
            32000,
            "Hũ",
            "Sữa chua vị vani lắc hạt dẻ cười",
            "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=500&auto=format&fit=crop",
        ),
        (
            "Bánh Tart Trứng Hongkong",
            "Tráng miệng & Bánh",
            25000,
            "Cái",
            "Bánh tart nướng vỏ giòn xốp nhân kem trứng",
            "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=500&auto=format&fit=crop",
        ),

        # --- ĐỒ UỐNG ĐÓNG CHAI (8 món) ---
        (
            "Coca Cola Lon 330ml",
            "Đồ uống đóng chai",
            20000,
            "Lon",
            "Nước ngọt có gas Coca Cola",
            "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=500&auto=format&fit=crop",
        ),
        (
            "Pepsi Không Calo",
            "Đồ uống đóng chai",
            20000,
            "Lon",
            "Pepsi vị chanh không đường",
            "https://images.unsplash.com/photo-1527960471264-932f39eb5846?w=500&auto=format&fit=crop",
        ),
        (
            "7Up Vị Chanh",
            "Đồ uống đóng chai",
            20000,
            "Lon",
            "Nước ngọt có gas 7Up",
            "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=500&auto=format&fit=crop",
        ),
        (
            "Redbull Thái Lon",
            "Đồ uống đóng chai",
            25000,
            "Lon",
            "Nước tăng lực Redbull Thái",
            "https://images.unsplash.com/photo-1527960471264-932f39eb5846?w=500&auto=format&fit=crop",
        ),
        (
            "Nước Khoáng Aquafina 500ml",
            "Đồ uống đóng chai",
            12000,
            "Chai",
            "Nước tinh khiết Aquafina",
            "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=500&auto=format&fit=crop",
        ),
        (
            "Soda Việt Quất Đá Xay",
            "Đồ uống đóng chai",
            38000,
            "Ly",
            "Soda sủi bọt mứt việt quất tươi",
            "https://images.unsplash.com/photo-1527960471264-932f39eb5846?w=500&auto=format&fit=crop",
        ),
        (
            "Soda Chanh Dây Mint",
            "Đồ uống đóng chai",
            38000,
            "Ly",
            "Soda chanh dây lá húng lủi mát lạnh",
            "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=500&auto=format&fit=crop",
        ),
        (
            "Cacao Nóng Marshmallow",
            "Đồ uống đóng chai",
            42000,
            "Tách",
            "Cacao Đắc Lắk nóng kẹo xốp",
            "https://images.unsplash.com/photo-1527960471264-932f39eb5846?w=500&auto=format&fit=crop",
        ),
    ]

    # 1. Khởi tạo danh mục
    category_names = list(set([item[1] for item in raw_products]))
    cat_map = {}
    for c_name in category_names:
        cat_obj, _ = Categories.objects.get_or_create(category_name=c_name)
        cat_map[c_name] = cat_obj

    # 2. Tạo đối tượng Product từ dữ liệu mảng
    product_objects = []
    for name, cat_name, price, unit, desc, image_url in raw_products:
        category_obj = cat_map.get(cat_name)
        cost_price = round(price * random.uniform(0.40, 0.52), 2)
        stock_qty = random.randint(50, 200)

        product_objects.append(
            Product(
                product_name=name,
                category=category_obj,
                price=price,
                cost_price=cost_price,
                stock_quantity=stock_qty,
                unit=unit,
                description=desc,
                status="ACTIVE",
                image_avatar=image_url,
            )
        )

    Product.objects.bulk_create(product_objects)


def reverse_100_products(apps, schema_editor):
    """Rollback an toàn: Xóa đúng 100 sản phẩm theo tên đã được tạo"""
    Product = apps.get_model("products", "Product")
    product_names = [
        "Cà phê đen đá", "Cà phê sữa đá", "Bạc xỉu nóng/lạnh", "Espresso Single", "Espresso Double",
        "Americano Đá", "Cappuccino Nóng", "Latte Macchiato", "Mocha Caramel", "Cà phê Muối",
        "Cà phê Trứng", "Cà phê Cốt dừa", "Cold Brew Truyền thống", "Cold Brew Cam Sả", "Affogato Cà phê",
        "Trà Đào Cam Sả", "Trà Vải Hạt Chia", "Trà Dâu Tây Kem Cheese", "Trà Tắc Mật Ong", "Trà Sen Vàng",
        "Trà Mãng Cầu Tươi", "Trà Hoa Cúc Mật Ong", "Trà Matcha Latte", "Trà Sữa Trân Châu Đường Đen", "Trà Sữa Ô Long Nướng",
        "Trà Sữa Thái Xanh", "Trà Sữa Thái Đỏ", "Hồng Trà Macchiato", "Trà Bưởi Hồng Đỏ", "Trà Chanh Giã Tay",
        "Trà Kiều Mạch Sữa", "Trà Sữa Đậu Đỏ", "Trà Long Nhãn Hạt Bột Lọc", "Sinh Tố Bơ Dừa", "Sinh Tố Xoài Cát",
        "Sinh Tố Dâu Tây", "Sinh Tố Sapoche (Hồng Xiêm)", "Sinh Tố Mãng Cầu", "Sinh Tố Dừa Đá Xay", "Nước Ép Cam Tươi",
        "Nước Ép Dưa Hấu", "Nước Ép Táo Ép Lạnh", "Nước Ép Thơm (Dứa)", "Nước Ép Cà Rốt Mật Ong", "Nước Ép Ổi Hồng",
        "Nước Ép Củ Dền Cần Tây", "Nước Dừa Tươi Nguyên Trái", "Nước Cần Tây Táo Green Detox", "Phở Bò Tái Lăn", "Phở Gà Ta Thịt Đùi",
        "Bún Bò Huế Đặc Biệt", "Bún Chả Hà Nội", "Bánh Mì Thịt Nướng Barbecue", "Bánh Mì Chảo Đắc Biệt", "Cơm Tấm Sườn Bì Chả",
        "Cơm Chiên Dương Châu", "Cơm Gà Xối Mỡ", "Mì Quảng Gà Ta", "Bún Riêu Cua Đóng Gạch", "Hủ Tiếu Nam Vang Tôm Mực",
        "Bún Thịt Nướng Chả Giò", "Mì Xào Hải Sản Sa Tế", "Miến Gà Trộn Hà Nội", "Cơm Bò Lúc Lắc Quán", "Mì Ý Sốt Bò Băm Spaghetti",
        "Khoai Tây Chiên Bơ Tỏi", "Cá Viên Chiên Mắm Tỏi", "Bánh Khoai Môn Lệ Phố", "Nem Chua Rán Hà Nội", "Gà Popcorn Lắc Phô Mai",
        "Phô Mai Que Chiên Giòn", "Xúc Xích Đức Nướng Than", "Bánh Tráng Trộn Sài Gòn", "Bánh Tráng Nướng Đà Lạt", "Chả Giò Hải Sản Sốt Mayonnaise",
        "Há Cảo Hấp Tôm Thịt", "Xíu Mại Nướng Sốt Cà", "Chân Gà Sả Tắc Cay", "Tokbokki Sốt Cay Hàn Quốc", "Gỏi Cuốn Tôm Thịt (3 Cuốn)",
        "Bánh Tiramisu Truyền Thống", "Cheesecake Chanh Dây", "Bánh Mousse Dâu Tây", "Bánh Croissant Bơ Tỏi", "Bánh Donut Chocolate",
        "Chè Thái Thập Cẩm", "Chè Bưởi An Giang", "Chè Khúc Bạch Trái Cây", "Sữa Chua Nếp Cẩm", "Flan Caramel Nước Cốt Dừa",
        "Sữa Chua Hạt Dẻ Cười", "Bánh Tart Trứng Hongkong", "Coca Cola Lon 330ml", "Pepsi Không Calo", "7Up Vị Chanh",
        "Redbull Thái Lon", "Nước Khoáng Aquafina 500ml", "Soda Việt Quất Đá Xay", "Soda Chanh Dây Mint", "Cacao Nóng Marshmallow"
    ]
    Product.objects.filter(product_name__in=product_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_populate_all_avatar_images"),
    ]

    operations = [
        migrations.RunPython(seed_100_products, reverse_100_products),
    ]