# Generated by Django 4.2 on 2026-08-24 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_agent', '0002_chatmessage_chatsession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('ASSISTANT', 'Assistant'), ('SYSTEM', 'System')], max_length=20),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='chatmessage',
            table='chat_messages',
        ),
        migrations.AlterModelTable(
            name='chatsession',
            table='chat_sessions',
        ),
        migrations.CreateModel(
            name='DocumentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=255)),
                ('extracted_text', models.TextField(blank=True)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('anomaly_detected', models.BooleanField(default=False)),
                ('anomaly_reasons', models.JSONField(blank=True, default=list)),
                ('needs_human_review', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyzed_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'document_analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
