# Generated by Django 4.2 on 2026-08-27 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0003_alter_chatmessage_created_at_alter_chatmessage_role_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentAnalysis',
        ),
    ]
