# Generated by Django 4.2.30 on 2026-10-01 17:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0006_seed_100_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Số lượng tồn')),
                ('min_threshold', models.IntegerField(default=10, verbose_name='Ngưỡng cảnh báo tối thiểu')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='products.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Tồn kho sản phẩm',
                'verbose_name_plural': 'Danh sách tồn kho',
                'db_table': 'inventory_stocks',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã kho')),
                ('name', models.CharField(max_length=255, verbose_name='Tên kho')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Vị trí/Địa chỉ')),
                ('status', models.CharField(choices=[('ACTIVE', 'Đang hoạt động'), ('INACTIVE', 'Ngừng hoạt động')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'verbose_name': 'Kho hàng',
                'verbose_name_plural': 'Danh sách kho hàng',
                'db_table': 'inventory_warehouses',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IMPORT', 'Nhập kho'), ('EXPORT', 'Xuất kho / Bán hàng'), ('TRANSFER', 'Chuyển kho')], max_length=20, verbose_name='Loại giao dịch')),
                ('quantity', models.IntegerField(verbose_name='Số lượng')),
                ('reference_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mã tham chiếu (Đơn hàng/Phiếu nhập)')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.stock', verbose_name='Bản ghi tồn kho')),
            ],
            options={
                'verbose_name': 'Biến động kho',
                'verbose_name_plural': 'Lịch sử biến động kho',
                'db_table': 'inventory_stock_movements',
            },
        ),
        migrations.AddField(
            model_name='stock',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventory.warehouse', verbose_name='Kho lưu trữ'),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('product', 'warehouse')},
        ),
    ]
