# Generated by Django 4.2 on 2026-07-11 10:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bussiness_tables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bussiness_tables',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bussiness_tables',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
