# Generated by Django 4.2.30 on 2026-09-15 19:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bussiness_tables', '0002_bussiness_tables_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bussiness_tables',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='bussiness_tables',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
