# Generated by Django 4.2 on 2026-09-01 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'expense_categories',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='expenses',
            options={'ordering': ['-expense_date', '-created_at']},
        ),
        migrations.RenameField(
            model_name='expenses',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='expense_name',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='expense_type',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='expentse_date',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='note',
        ),
        migrations.AddField(
            model_name='expenses',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='expenses',
            name='expense_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='expenses',
            name='receipt_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='expenses',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Bản nháp'), ('CONFIRMED', 'Đã xác nhận'), ('CANCELLED', 'Đã hủy')], default='CONFIRMED', max_length=20),
        ),
        migrations.AddField(
            model_name='expenses',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='expenses',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expenses',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='expenses.expensecategory'),
        ),
    ]
