# Generated by Django 4.2 on 2026-09-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expensecategory_alter_expenses_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='supplier_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nhà cung cấp / Bên nhận'),
        ),
    ]
