# Generated by Django 4.2 on 2026-09-01 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentanalysis',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Chờ xác nhận'), ('CONFIRMED', 'Đã xác nhận'), ('REJECTED', 'Đã từ chối')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentanalysis',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_analyses', to=settings.AUTH_USER_MODEL),
        ),
    ]
